main.exe: main.cpp glm.cpp mtxlib.cpp trackball.cpp
	g++ main.cpp glm.cpp mtxlib.cpp trackball.cpp -o main.exe -L"E:\Learner\DeepLearning\Msys64\mingw64\lib" -lfreeglut -lopengl32 -lglu32 -lopenal -lwinmm

clean:
	del main.exe
